# Simple workflow for deploying static content to GitHub Pages
name: Deploy documentation to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ${{ github.repository_owner == 'oneapi-src' && 'intel-ubuntu-22.04' || 'ubuntu-latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: 3.9

      - name: Install apt package
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Install prerequisites
        run: python3 -m pip install -r third_party/requirements.txt

      - name: Setup Pages
        uses: actions/configure-pages@1f0c5cde4bc74cd7e1254d0cb4de8d49e9068c7d # v4.0.0

      - name: Build Documentation
        working-directory: ${{github.workspace}}/scripts
        run: |
          python3 run.py --core
          mkdir -p ${{ github.workspace }}/ur-repo/
          mkdir -p ${{github.workspace}}/docs/html

      - name: Checkout benchmark scripts
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: intel/llvm
          ref: unify-benchmark-ci
          path: sc
          sparse-checkout: |
            devops/scripts/benchmarks

      - name: Move benchmark HTML files
        run: |
          mkdir -p ${{ github.workspace }}/docs/html/performance
          mv ${{ github.workspace }}/sc/devops/scripts/benchmarks/html/* ${{ github.workspace }}/docs/html/performance/

      - name: Replace config.js
        run: |
          cat << 'EOF' > ${{ github.workspace }}/docs/html/performance/config.js
          remoteDataUrl = 'https://raw.githubusercontent.com/oneapi-src/unified-runtime/refs/heads/benchmark-results/data.json';
          defaultCompareNames = ["Baseline_PVC_L0", "Baseline_PVC_L0v2"];
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@0252fc4ba7626f0298f0cf00902a25c6afc77fa8 # v3.0.0
        with:
          path: ${{github.workspace}}/docs/html

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ${{ github.repository_owner == 'oneapi-src' && 'intel-ubuntu-22.04' || 'ubuntu-latest' }}
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@87c3283f01cd6fe19a0ab93a23b2f6fcba5a8e42 # v4.0.3
